# Tensor和数据类型示例

In [6]:
import torch

均匀分布

In [7]:
x = torch.rand(2, 3)
x

tensor([[0.7810, 0.2079, 0.2512],
        [0.4063, 0.5217, 0.3980]])

正态分布

In [8]:
x = torch.randn(2, 3)
x

tensor([[-1.6037,  0.4321,  0.0127],
        [ 0.9946,  1.9843,  0.5131]])

全0矩阵

In [9]:
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

单位矩阵

In [10]:
x = torch.ones(2, 3, 4)
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

查看形状

In [11]:
x.size()

torch.Size([2, 3, 4])

In [12]:
x.size(0)

2

---
## 基本数据类型

In [13]:
torch.float32
torch.float64
torch.int32
torch.int64
torch.int16

torch.int16

创建一个Tensor张量

In [17]:
x = torch.tensor([6, 2], dtype=torch.int64)
x

tensor([6, 2])

In [18]:
x.type(dtype=torch.float64)
x

tensor([6, 2])

## tensor和ndarray转化

In [34]:
import numpy as np

In [36]:
a = np.random.randn(2, 3)
a

array([[-1.79601622,  0.80445669, -0.42373675],
       [-0.39425979,  1.18474146, -0.72255217]])

In [37]:
x1 = torch.from_numpy(a)
x1

tensor([[-1.7960,  0.8045, -0.4237],
        [-0.3943,  1.1847, -0.7226]], dtype=torch.float64)

---
## tensor运算

In [46]:
x2 = torch.rand(2, 3)
x2

tensor([[0.3633, 0.1163, 0.1602],
        [0.9692, 0.5580, 0.1216]])

相加

In [47]:
# 相加1
x1 + x2

tensor([[-1.4327,  0.9207, -0.2636],
        [ 0.5749,  1.7428, -0.6010]], dtype=torch.float64)

In [48]:
# 相加2
x1.add(x2)

tensor([[-1.4327,  0.9207, -0.2636],
        [ 0.5749,  1.7428, -0.6010]], dtype=torch.float64)

In [50]:
# 相加直接赋值
x1.add_(x2)

tensor([[-1.4327,  0.9207, -0.2636],
        [ 0.5749,  1.7428, -0.6010]], dtype=torch.float64)

变换

In [61]:
x1.view(3, 2) # 变换为（3，2）

tensor([[-1.4327,  0.9207],
        [-0.2636,  0.5749],
        [ 1.7428, -0.6010]], dtype=torch.float64)

In [62]:
x1.view(-1, 1)  # -1表示自动计算个数，即shape（n，1）

tensor([[-1.4327],
        [ 0.9207],
        [-0.2636],
        [ 0.5749],
        [ 1.7428],
        [-0.6010]], dtype=torch.float64)

获得标量值

In [63]:
mean = x1.mean()
mean.item()

0.15686859209721768

---
## tensor的自动微分
tensor的数据结构：
data 数值标量;
grad 梯度（运算中产生）;
grad_fn 该张量运算对应的微分函数

In [19]:
x = torch.ones(2, 3, requires_grad=True)

In [20]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [21]:
# 线性变换
y = 2 * x + 3

In [22]:
y

tensor([[5., 5., 5.],
        [5., 5., 5.]], grad_fn=<AddBackward0>)

In [23]:
# 再次运算
z = y * y + 5

In [24]:
z

tensor([[30., 30., 30.],
        [30., 30., 30.]], grad_fn=<AddBackward0>)

In [25]:
# 均值输出
out = z.mean()

In [26]:
out

tensor(30., grad_fn=<MeanBackward0>)

<center>
$out=F(x)$
</center>
<center>
$grad=\frac{\partial F(x)}{\partial x}$
</center>

In [27]:
out.backward()
x.grad

tensor([[3.3333, 3.3333, 3.3333],
        [3.3333, 3.3333, 3.3333]])